# Generated by Django 3.0.3 on 2020-04-05 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0002_score_store'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='name',
            new_name='name_en',
        ),
        migrations.AddField(
            model_name='pizza',
            name='image',
            field=models.URLField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='pizza',
            name='name_kr',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
